name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app
            git -C fullstackapp-client fetch origin master
            git -C fullstackapp-client reset --hard origin/master
            git -C fullstackapp-server fetch origin master
            git -C fullstackapp-server reset --hard origin/master
            docker compose down
            docker compose up -d --build
